import = ["~/.config/alacritty/catppuccin.toml"]
shell = "/bin/zsh"
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
startup_mode= "Maximized"
decorations = "Full"

[keyboard]
bindings = [{ key = "F", mods = "Control", chars= "fzf -e -q "}, ]
